Pizza maker
track-town-pizza/capstone pull request #33
Opened 2020-03-03 07:50 UTC by hillkai

Pizza Builder stuff completed...finally

2020-03-04 19:43 UTC, Aidenjn requested changes
Looks quite good! When we meet today I may ask a few questions on how the half and half pizza pricing works.
One thing that I noticed was that there is no way to navigate to the pizza builder page (button on pizza menu page doesn't link to this).
Another thing that would be nice but probably not essential, is a way to "lock" the sides until the user selects a size, crust, and cheese, similar to like you do with the gluten free crust option. Right now I can build pizzas that consist of only sides that cost $0.

2020-03-04 22:36 UTC, HannahTierneyV reviewed
Everything looks good! Great job finishing this beast of a feature. The only reason I'm not explicitly approving the PR right away is because Aiden requested changes and I want to give you a chance to address those first.

2020-03-04 22:36 UTC, HannahTierneyV commented on data/restaurantInfo.json
> +}
This will eventually need to be replaced/combined with the info.json file I originally created for the home page, but fortunately the values are the same and that should be a really easy and quick fix!

2020-03-05 06:00 UTC, Aidenjn commented
looks good!

2020-03-05 06:01 UTC, Aidenjn approved these changes

2020-03-05 06:04 UTC, Aidenjn requested changes
need to move buffet and drinks into menu folder and fix links

2020-03-11 01:49 UTC, merged